services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: trafyx-backend
    env_file:
      - ./apps/backend/.env
    environment:
      - PORT=5000
      - GIN_MODE=release
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: trafyx-frontend
    env_file:
      - ./apps/frontend/.env
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: trafyx-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./apps/backend/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./apps/backend/certbot/conf:/etc/letsencrypt
      - ./apps/backend/certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: trafyx-certbot
    volumes:
      - ./apps/backend/certbot/conf:/etc/letsencrypt
      - ./apps/backend/certbot/www:/var/www/certbot
    depends_on:
      - nginx
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
